### ISSUE TITLE
ESP3D Update and Filesystem panels

### ISSUE THREAD

**Issue by axl12ap** [luc-github/ESP3D#271]
Good afternoon,
what can I do with "ESP3D Update" menu into Webserver? There's an option to upload a file... but no explain what and how to do..

And again, ESP3D Filesystem can contain only data for ESP3D firmware?
It must be so good if I'll can put on this filesystem (on Wemos D1 mini pro huge, 14MB) some gcode to print for my printer, instead from printer SD..

**Comment by luc-github** [comment]
* ESP3D Update is to Update ESP3D Firmware - this feature is mentioned in both read me of ESPD3D and ESP3D-WEBUI
* you can upload any file, but I do not see how FW printer can access to SPIFFS of ESP8266
and just case you ask : no ! ESP8266 can not act as host in same time with all all others current features because of ESP8266 performances.  ESP32 could but not ESP8266
Using ESP8266 as pure host need another Firmware not ESP3D

**Comment by luc-github** [comment]
I guess issue can be closed
