### ISSUE TITLE
Excruciatingly slow WiFi upload

### ISSUE THREAD

**Issue by ModMike** [luc-github/ESP3D#276]
I know this has been discussed nearly 2 years ago but has there been any improvements?  Are any coming?

**Comment by luc-github** [comment]
What is slow ?  What reference can you give ?
On my side it is Ok

**Comment by luc-github** [comment]
Serial upload is using M28/M29 protocol over wifi
Direct SD is direct access from ESP to SD over wifi

On my side 63.54MB take 4:30 min with SPI speed 4X on SD class 10, I did not bench since a while to be honest.

I have tried Flash air Upload and it is indeed faster as it took 1:30 min, but it is different hardware and software. 

The upload to SD only depend on SD library,  SPI Speed and SD card type as the code itself  is minimal - need to test to see what parameter to tune to increase speed if possible

**Comment by ModMike** [comment]
Would increasing baud rate help in any way or am I completely off base?

**Comment by luc-github** [comment]
ESP is directly connected to SD card on Azteeg WiFi - serial is used for communication with board, as ESP directly write to SD, changing baud rate won't affect upload to SD

**Comment by luc-github** [comment]
There are a lot of change coming with ESP8266 core 2.5 - need to test when done as currently there are too many daily change to validate anything - better to wait the release
Also this issue does not happen to this repo (no direct SD access) - only to customized code which is not here - so issue can be closed
