### ISSUE TITLE
Proposal: Rename Project

### ISSUE THREAD

**Issue by openhardwarecoza** [luc-github/ESP3D#91]
I know this is not an easy one, but it would be helpful to get a more descriptive name, like ESP8266-reprap?

**Comment by luc-github** [comment]
well I will work on smoothiware support soon and it is not really reprap - I agree ESP8266 is too light but github description is  there - and because now many links point to this name , to change the name means to create a new github with new name and create a redirection on current one to new one.
I do not sure it worth 
about arduino project file and directory itself  inside GitHub- I think it is ok, I was also thinking about new ino file like : ESP_for_3Dprinter but looking for shorter one

**Comment by TRoager** [comment]
ESP3D?

**Comment by luc-github** [comment]
Yes could be a good candidate :smile:

**Comment by openhardwarecoza** [comment]
I like esp3d!

**Comment by luc-github** [comment]
seems forward feature is available : https://github.com/blog/1508-repository-redirects-are-here
so I will rename repository as well after some tests

**Comment by luc-github** [comment]
I have validated that renaming a repository keep forwarding previous github address to new one - so far so good

If no one comment against this I will change this week from ESP8266 to ESP3D as I did not found another similar project with same name

**Comment by TRoager** [comment]
Yay i had an impact on the name :D

**Comment by luc-github** [comment]
what about a logo if name is defined ?
![image](https://cloud.githubusercontent.com/assets/8822552/15891325/501bdf12-2d74-11e6-959d-be7d3438b8f2.png)

**Comment by TRoager** [comment]
I agree there should be a logo but not sure if thats the logo for the project but im no designer so can't help there :p

**Comment by luc-github** [comment]
me neither but I am sure you saw it :smile:

paint.net my limit

**Comment by luc-github** [comment]
Ok, code is modified / links are updated  / readme is updated - I will change name tomorrow and push changes to match new name just after.

**Comment by luc-github** [comment]
Name modification is done - thank you guys
